apiVersion: apps/v1
kind: Deployment

metadata:
  name: broadcaster-dep
spec:
  template:
    spec:
      containers:
      - name: broadcaster
        env:
        - name: FORWARD_TO_EXTERNAL_SERVICE
          value: "false"
