apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-svc
  labels:
    app: postgresql-db
spec:
  ports:
  - port: 5432
    name: postgressql
  clusterIP: None
  selector:
    app: postgresql-db
