apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
stringData:
  # echo -n "testdbuserpassword" | base64
  # dGVzdGRidXNlcnBhc3N3b3Jk
  # POSTGRES_PASSWORD: dGVzdGRidXNlcnBhc3N3b3Jk
  POSTGRES_PASSWORD: testdbuserpassword
