apiVersion: apps/v1
kind: Deployment

metadata:
  name: broadcaster-dep
spec:
  template:
    spec:
      containers:
      - name: broadcaster
        env:
        - name: FORWARD_TO_EXTERNAL_SERVICE
          value: "true"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook-secret
              key: webhook_url
