apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-project-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arkb2023/todo-app-configs.git
    path: apps/the-project/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
